default_platform(:android)

platform :android do

    desc "Lane for distributing app using Firebase App Distributions"
    lane :distributeDebug do
        gradle(task: "clean :android:assembleDebug")

        version_name = get_version_name(
              gradle_file_path:"android/build/generated/source/buildConfig/debug/app/saboten/androidApp/BuildConfig.java",
              ext_constant_name:"VERSION_NAME"
        ).delete_suffix(";")

        version_code = get_version_name(
              gradle_file_path:"android/build/generated/source/buildConfig/debug/app/saboten/androidApp/BuildConfig.java",
              ext_constant_name:"VERSION_CODE"
        ).delete_suffix(";")

        firebase_app_distribution(
            service_credentials_file: "firebase_credentials.json",
            app: ENV['FAD_ANDROID_APP_ID'],
            release_notes_file: "fastlane/metadata/android/ko-KR/changelogs/debug-release-notes.txt",
            groups: "all"
        )

        release_notes = File.read("metadata/android/ko-KR/changelogs/debug-release-notes.txt")

        slack(
           message: ":rocket: 몹시 싱싱한 빌드가 업로드 되었습니다. :cactus:",
           success: true,
           slack_url: "https://hooks.slack.com/services/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",
           default_payloads: [:git_branch, :last_git_commit_message],
           attachment_properties: {
               fields: [
                   {
                       title: "항상 감사하십시오",
                       value: "https://appdistribution.firebase.dev/i/506c2a6476f45a3d",
                   },
                   {
                       title: "Version",
                       value: "#{version_name}(#{version_code})"
                   },
                   {
                       title: "Release Notes",
                       value: release_notes
                   },
                   {
                       title: "APK 다운로드 링크 (1시간 후 만료)",
                       value: binary_download_uri
                   }
               ]
           }
        )
    end

    error do |lane, exception, options|
        slack(
               message: "불발쇼! 빌드에 실패했습니다. :rage:",
               success: false,
               slack_url: "https://hooks.slack.com/services/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",
               default_payloads: [:git_branch, :last_git_commit_message],
               attachment_properties: {
                   fields: [
                       {
                           title: "반성하십시오 고치세요",
                           value: exception
                       },
                       {
                           title: "Version",
                           value: "#{version_name}(#{version_code})"
                       }
                   ]
               }
           )
    end

end