name: Backend Dev Deploy to GCE

on:
  push:
    branches: [ release-server/* ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # application-dev.properties 생성
      - name: Create Spring Properties
        run: |
          touch server/src/main/resources/application-dev.properties
          echo "$DEV_SPRING_PROPERTIES" > application-dev.properties.b64
          base64 -d -i application-dev.properties.b64 > server/src/main/resources/application-dev.properties
        env:
          DEV_SPRING_PROPERTIES: ${{ secrets.DEV_SPRING_PROPERTIES }}

      - name: Build with Gradle
        run: |
          ./gradlew clean :server:build -Pprofile=dev    

      - name: Move to DockerFile Directory
        run: cd server

      - name: Docker build
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
  # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}

#      - name: Deploy to Heroku
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          usedocker: true
