name: Backend Dev Deploy to GCS

on:
  push:
    branches: [ feature/SBOT-55 ]

env:
  PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # application-dev.properties 생성
      - name: Create Spring Properties
        run: |
          touch server/src/main/resources/application-dev.properties
          echo "DEV_SPRING_PROPERTIES" > application-dev.properties.b64
          base64 -d -i application-dev.properties.b64 > server/src/main/resources/application-dev.properties
        env:
          DEV_SPRING_PROPERTIES: ${{ secrets.DEV_SPRING_PROPERTIES }}

      - name: Build with Gradle
        run: |
          ./gradlew clean :server:build -Pprofile=dev

# 일단 이거는 기본적인 Docker build이고 밑에서 docker build 쓸거 같음
#      - name: Docker build
#        run: docker build -t spring-saboten-image .

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCS_PROJECT_ID }}
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
      gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA" .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"
      - name: Deploy
        run: |-
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"