name: Backend Dev Deploy to GCE

on:
  push:
    branches: [ release-server/* ]

env:
  OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVKEY_FILE }}
  OCI_CLI_REGION: ${{ secrets.OCI_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # application-dev.properties 생성
      - name: Create Spring Properties
        run: |
          touch server/src/main/resources/application-dev.properties
          echo "$DEV_SPRING_PROPERTIES" > application-dev.properties.b64
          base64 -d -i application-dev.properties.b64 > server/src/main/resources/application-dev.properties
        env:
          DEV_SPRING_PROPERTIES: ${{ secrets.DEV_SPRING_PROPERTIES }}

      - name: Build with Gradle
        run: |
          ./gradlew clean :server:build -Pprofile=dev      

      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag saboten/api
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push saboten/api

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_REMOTE_IP }}
          username: ${{ secrets.OCI_REMOTE_SSH_ID }}
          key: ${{ secrets.OCI_REMOTE_SSH_KEY }}
          port: ${{ secrets.OCI_REMOTE_SSH_PORT }}
          script: |
            docker pull saboten/api
            docker run --name saboten-api -p 8080:8080 saboten/api